import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 20,
    color: '#006385',
    flex: 1,
  },
  button: {
    fontSize: 200,
    textAlign: 'center',
    backgroundColor: '#006385',
  },
  paragraph: {
    marginTop: 150,
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#006385',
    marginBottom: 0,
    fontFamily: 'Montserrat_400Regular',
  },

  paragraphQR: {
    marginTop: 0,
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
    color: '#006385',
    marginBottom: 10,
  },

  qr: {
    marginTop: 30,
    width: 200,
    height: 300,
    marginBottom: 70,
  },

  buttonChooseSearchingMethod: {
    borderBottomColor: '#737373',
    padding: 50,
    color: 'red',
  },

  textInput: {
    height: 40,
    margin: 12,
    borderWidth: 1,
    padding: 10,
    fontFamily: 'Montserrat_400Regular',
  },

  input: {
    height: 40,
    margin: 12,
    borderWidth: 1,
    padding: 20,
    borderRadius: 10,
    width: '80%',
    color: 'black',
    backgroundColor: 'white',
    fontFamily: 'Montserrat_400Regular',
    paddingVertical: 0,
  },

  background: {
    width: '100%',
    height: '100%',
    backgroundColor: '#bbcbe4',
  },
  background2: {
    width: '100%',
    height: '100%',
  },
  logo: {
    width: 280,
    height: 280,
    marginLeft: '15%',
    marginTop: '10%',
  },
  text: {
    color: 'white',
    marginTop: '-15%',
    marginLeft: '15%',
    fontFamily: 'Montserrat_400Regular',
  },
  textChoose: {
    color: '#2b3858',
    fontSize: 50,
    textAlign: 'center',
    marginHorizontal: 20,
    fontFamily: 'Montserrat_400Regular',
  },
  getstartedBtn: {
    backgroundColor: '#79a1f8',
    color: 'white',
    width: '65%',
    borderRadius: 13,
    textAlign: 'center',
    marginLeft: '18%',
    padding: '2%',
    fontSize: 23,
    overflow: 'hidden',
    fontFamily: 'Montserrat_400Regular',
  },
  chooseBtn1: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#2b3858',
    width: '90%',
    borderRadius: 10,
    textAlign: 'left',
    fontSize: 18,
    padding: 9,

    color: '#2b3858',
    marginHorizontal: 20,
    fontFamily: 'Montserrat_400Regular',

    top: 5,
  },
  chooseBtn2: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#2b3858',
    width: '98%',
    borderRadius: 10,
    textAlign: 'left',
    fontSize: 18,
    padding: 9,
    color: '#2b3858',
    marginHorizontal: 20,
    top: 7,
    fontFamily: 'Montserrat_400Regular',
  },
  buttonContainer: {
    flex: 1,
    color: 'black',
  },

  //steps

  stepFinished: {
    width: '65%',
    borderRadius: 13,
    textAlign: 'center',
    fontSize: 23,
    overflow: 'hidden',
    fontFamily: 'Montserrat_400Regular',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#8DB255',
    textShadowRadius: 10,
    borderWidth: 3,
    borderColor: '#dad7d7',
    padding: '2%',

    margin: 22,
    backgroundColor: '#d0f5ae',
    textDecorationLine: 'line-through',
  },

  stepCurrent: {
    width: '65%',
    borderRadius: 13,
    textAlign: 'center',
    padding: '2%',
    fontSize: 23,
    overflow: 'hidden',
    fontFamily: 'Montserrat_400Regular',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#006385',
    textShadowRadius: 10,
    borderWidth: 3,
    borderColor: '#006385',

    margin: 22,
    backgroundColor: 'white',
  },
  stepNext: {
    width: '65%',
    borderRadius: 13,
    textAlign: 'center',
    padding: '2%',
    fontSize: 23,
    overflow: 'hidden',
    fontFamily: 'Montserrat_400Regular',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#ded9d9',
    textShadowRadius: 10,
    borderWidth: 3,
    borderColor: '#dad7d7',
    margin: 22,
    disabled: 'true',
  },

  stepBtn: {
    backgroundColor: '#d0f5ae',
    color: 'white',
    width: '65%',
    borderRadius: 13,
    textAlign: 'center',
    marginLeft: '18%',
    padding: '2%',
    fontSize: 23,
    overflow: 'hidden',
    fontFamily: 'Montserrat_400Regular',
  },
  languageBtn: {
    fontSize: 25,
  },
  galleryBtn: {
    backgroundColor: 'none',
    color: '#79a1f8',
    width: '65%',
    borderRadius: 13,
   
    marginLeft: '18%',
    padding: '2%',
    fontSize: 20,
    overflow: 'hidden',
    fontFamily: 'Montserrat_100Thin',
    borderWidth: 1,
    borderColor: '#79a1f8',
        textAlign: 'center',

  },
});